### ISSUE TITLE
Super Trainers

### ISSUE THREAD

**Issue by dtwitty** [dtwitty/MNIST_ML#4]
We need automatic parameter selection for our models. Specifically, we should have long-running methods for each model that exhaustively choose combinations of parameters, run cross-validation, and spit out the best parameters. 

Caveats: We should run these after cherry-picking our features because I expect them to take a _long_ time, like overnight. 

For SVM, we should pick:
nu, kernel type, kernel-specific params

For Neural Net:
number of layers, layer sizes

For KNN:
k

**Comment by Codeacious** [comment]
"After 9 years in development, hopefully, it will have been worth the wait."

**Comment by dtwitty** [comment]
Really this entire project should be redone in scikit-learn. Please use industry-standard tooling.
